/*  ------------------------------------------------------
     Routine name:  msh65
     Description:   
     Project file:  Шаблон для msh65.prt

------------------------------------------------------  */

int i;
int j;
int c;
ret = 0;
memcpy(&state_vars->msh65v0_out_0_,&msh65v0_out_0_default,sizeof(msh65v0_out_0_default));
memcpy(&state_vars->msh65v1_out_0_,&msh65v1_out_0_default,sizeof(msh65v1_out_0_default));
