/*  ------------------------------------------------------
     Routine name:  msh65
     Description:   
     Project file:  Шаблон для msh65.prt

------------------------------------------------------  */

/*       Local stack variables                */
int i;
int j;
int c;
int itmp1;
int itmp2;
double tmp1;
double tmp2;
double tmp3;
double tmp4;
double tmp5;
double tmp6;
double tmp7;
char f;
char tmp_f_1;
char u_s;
char u_r;

 
 SHAR_INPUT_DATA msh65v1_input;
 
 SHAR_INPUT_65DATA msh65v1_out; 
 
 
ret = 0;

