/*  ------------------------------------------------------
     Routine name:  test
     Description:   
     Project file:  Шаблон.prt

------------------------------------------------------  */

int i;
int j;
int c;
ret = 0;
memcpy(&testv2_out_0,&testv2_out_0_default,sizeof(testv2_out_0_default));
memcpy(&testv3_x,&testv3_x_default,sizeof(testv3_x_default));
memcpy(&state_vars->testv0_out_0_,&testv0_out_0_default,sizeof(testv0_out_0_default));
memcpy(&state_vars->testv1_out_0_,&testv1_out_0_default,sizeof(testv1_out_0_default));
memcpy(&state_vars->testv3_out_0_,&testv3_out_0_default,sizeof(testv3_out_0_default));
memcpy(&consts->testv2_k_,&testv2_k_default,sizeof(testv2_k_default));
memcpy(&consts->testv2_t_,&testv2_t_default,sizeof(testv2_t_default));
memcpy(&consts->testv3_k_,&testv3_k_default,sizeof(testv3_k_default));
memcpy(&consts->testv3_ymin_,&testv3_ymin_default,sizeof(testv3_ymin_default));
memcpy(&consts->testv3_ymax_,&testv3_ymax_default,sizeof(testv3_ymax_default));
