/*  ------------------------------------------------------
     Routine name:  datarcv
        Generated:  29.09.2013 18:45:56
      Description:  
     Project file:  sample_data_source.prt

------------------------------------------------------  */

/*       Local stack variables                */
int i;
int j;
int c;
double tmp1;
double tmp2;
double tmp3;
double tmp4;
double tmp5;
double tmp6;
char f;
char tmp_f_1;
char u_s;
char u_r;
ret = 0;

