/*  ------------------------------------------------------
     Routine name:  datarcv
        Generated:  29.09.2013 18:45:56
      Description:  
     Project file:  sample_data_source.prt

------------------------------------------------------  */

int i;
int c;
ret = 0;
memcpy(&data1,&data1_default,sizeof(data1_default));
memcpy(&data2,&data2_default,sizeof(data2_default));
memcpy(&data3,&data3_default,sizeof(data3_default));
memcpy(&datarcvv0_loct,&datarcvv0_loct_default,sizeof(datarcvv0_loct_default));
memcpy(&datarcvv0_a,&datarcvv0_a_default,sizeof(datarcvv0_a_default));
memcpy(&datarcvv0_w,&datarcvv0_w_default,sizeof(datarcvv0_w_default));
memcpy(&datarcvv0_f,&datarcvv0_f_default,sizeof(datarcvv0_f_default));
