/*  ------------------------------------------------------
     Routine name:  myblock
        Generated:  02.12.2011 11:55:27
      Description:  
     Project file:  Самогенерирующийся блок.prt

------------------------------------------------------  */

/*       Local stack variables                */
int i;
int j;
int c;
double tmp1;
char f;
char u_s;
char u_r;
  
static double v1_w = 100;
ret = 0;


/* Index=1
   UID=1
   GeneratorClassName=TLanguage
   Name=SelfGenTemplate
   Type=Самогенерирующийся блок */

myblockv1_out_0=myblockv1_out_0+1;
