/*  ------------------------------------------------------
     Routine name:  myblock
        Generated:  02.12.2011 11:55:27
      Description:  
     Project file:  Самогенерирующийся блок.prt

------------------------------------------------------  */

ret = 0;
memcpy(&myblockv1_dyn_var,&myblockv1_dyn_var_default,sizeof(myblockv1_dyn_var_default));
memcpy(&myblockv0_out_0,&myblockv0_out_0_default,sizeof(myblockv0_out_0_default));
memcpy(&myblockv1_out_0,&myblockv1_out_0_default,sizeof(myblockv1_out_0_default));
myblockv1_out_0=1;
