/*  ------------------------------------------------------
     Routine name:  bup_pwm
     Description:   
     Project file:  Шаблон.prt

------------------------------------------------------  */

int i;
int j;
int c;
ret = 0;
memcpy(&state_vars->bup_pwmv6cd2d8_out_0_,&bup_pwmv6cd2d8_out_0_default,sizeof(bup_pwmv6cd2d8_out_0_default));
memcpy(&state_vars->bup_pwmve62922_out_0_,&bup_pwmve62922_out_0_default,sizeof(bup_pwmve62922_out_0_default));
memcpy(&state_vars->bup_pwmv7db3a6_out_0_,&bup_pwmv7db3a6_out_0_default,sizeof(bup_pwmv7db3a6_out_0_default));
memcpy(&state_vars->bup_pwmve33be5_out_0_,&bup_pwmve33be5_out_0_default,sizeof(bup_pwmve33be5_out_0_default));
memcpy(&state_vars->bup_pwmve33be5_vskor_,&bup_pwmve33be5_vskor_default,sizeof(bup_pwmve33be5_vskor_default));
memcpy(&state_vars->bup_pwmve33be5_vdelta_,&bup_pwmve33be5_vdelta_default,sizeof(bup_pwmve33be5_vdelta_default));
memcpy(&state_vars->bup_pwmve33be5_pwm_,&bup_pwmve33be5_pwm_default,sizeof(bup_pwmve33be5_pwm_default));
memcpy(&state_vars->bup_pwmvf52b10_out_0_,&bup_pwmvf52b10_out_0_default,sizeof(bup_pwmvf52b10_out_0_default));
memcpy(&state_vars->bup_pwmv88b3b3_out_0_,&bup_pwmv88b3b3_out_0_default,sizeof(bup_pwmv88b3b3_out_0_default));
memcpy(&state_vars->bup_pwmv5193f6_out_0_,&bup_pwmv5193f6_out_0_default,sizeof(bup_pwmv5193f6_out_0_default));
