/*  ------------------------------------------------------
     Routine name:  bup_pwm
     Description:   
     Project file:  ״אבכמם הכÿ ֱ׃ֿ.prt

------------------------------------------------------  */

/*       Local stack variables                */
int i;
int j;
int c;
int itmp1;
int itmp2;
double tmp1;
double tmp2;
double tmp3;
double tmp4;
double tmp5;
double tmp6;
double tmp7;
char f;
char tmp_f_1;
char u_s;
char u_r;
int bup_pwmv6_vskor_temp;
int bup_pwmv6_vdelta_temp;
 
ret = 0;

