/*  ------------------------------------------------------
     Routine name:  bup_pwm
     Description:   
     Project file:  ״אבכמם הכÿ ֱ׃ֿ.prt

------------------------------------------------------  */

int i;
int j;
int c;
ret = 0;
memcpy(&state_vars->bup_pwmv3_out_0_,&bup_pwmv3_out_0_default,sizeof(bup_pwmv3_out_0_default));
memcpy(&state_vars->bup_pwmv4_out_0_,&bup_pwmv4_out_0_default,sizeof(bup_pwmv4_out_0_default));
memcpy(&state_vars->bup_pwmv5_out_0_,&bup_pwmv5_out_0_default,sizeof(bup_pwmv5_out_0_default));
memcpy(&state_vars->bup_pwmv6_out_0_,&bup_pwmv6_out_0_default,sizeof(bup_pwmv6_out_0_default));
memcpy(&state_vars->bup_pwmv6_vskor_,&bup_pwmv6_vskor_default,sizeof(bup_pwmv6_vskor_default));
memcpy(&state_vars->bup_pwmv6_vdelta_,&bup_pwmv6_vdelta_default,sizeof(bup_pwmv6_vdelta_default));
memcpy(&state_vars->bup_pwmv6_pwm_,&bup_pwmv6_pwm_default,sizeof(bup_pwmv6_pwm_default));
memcpy(&state_vars->bup_pwmv0_out_0_,&bup_pwmv0_out_0_default,sizeof(bup_pwmv0_out_0_default));
memcpy(&state_vars->bup_pwmv1_out_0_,&bup_pwmv1_out_0_default,sizeof(bup_pwmv1_out_0_default));
memcpy(&state_vars->bup_pwmv2_out_0_,&bup_pwmv2_out_0_default,sizeof(bup_pwmv2_out_0_default));
