/*  ------------------------------------------------------
     Routine name:  firstactivetest
        Generated:  02.02.2015 20:01:09
      Description:  
     Project file:  Выбор номера ненулевого элемента и case.prt

------------------------------------------------------  */

int i;
int c;
ret = 0;
memcpy(&state_vars->v0_out_0_,&v0_out_0_default,sizeof(v0_out_0_default));
memcpy(&state_vars->firstactivetestv0_loct_,&firstactivetestv0_loct_default,sizeof(firstactivetestv0_loct_default));
memcpy(&state_vars->firstactivetestv1_out_0_,&firstactivetestv1_out_0_default,sizeof(firstactivetestv1_out_0_default));
memcpy(&state_vars->firstactivetestv1_timer_,&firstactivetestv1_timer_default,sizeof(firstactivetestv1_timer_default));
memcpy(&state_vars->firstactivetestv2_out_0_,&firstactivetestv2_out_0_default,sizeof(firstactivetestv2_out_0_default));
memcpy(&state_vars->firstactivetestv2_timer_,&firstactivetestv2_timer_default,sizeof(firstactivetestv2_timer_default));
memcpy(&state_vars->firstactivetestv3_out_0_,&firstactivetestv3_out_0_default,sizeof(firstactivetestv3_out_0_default));
memcpy(&state_vars->firstactivetestv3_timer_,&firstactivetestv3_timer_default,sizeof(firstactivetestv3_timer_default));
memcpy(&consts->firstactivetestv0_a_,&firstactivetestv0_a_default,sizeof(firstactivetestv0_a_default));
memcpy(&consts->firstactivetestv0_w_,&firstactivetestv0_w_default,sizeof(firstactivetestv0_w_default));
memcpy(&consts->firstactivetestv0_f_,&firstactivetestv0_f_default,sizeof(firstactivetestv0_f_default));
memcpy(&consts->firstactivetestv1_t1_,&firstactivetestv1_t1_default,sizeof(firstactivetestv1_t1_default));
memcpy(&consts->firstactivetestv1_t2_,&firstactivetestv1_t2_default,sizeof(firstactivetestv1_t2_default));
memcpy(&consts->firstactivetestv1_y1_,&firstactivetestv1_y1_default,sizeof(firstactivetestv1_y1_default));
memcpy(&consts->firstactivetestv1_y2_,&firstactivetestv1_y2_default,sizeof(firstactivetestv1_y2_default));
memcpy(&consts->firstactivetestv2_t1_,&firstactivetestv2_t1_default,sizeof(firstactivetestv2_t1_default));
memcpy(&consts->firstactivetestv2_t2_,&firstactivetestv2_t2_default,sizeof(firstactivetestv2_t2_default));
memcpy(&consts->firstactivetestv2_y1_,&firstactivetestv2_y1_default,sizeof(firstactivetestv2_y1_default));
memcpy(&consts->firstactivetestv2_y2_,&firstactivetestv2_y2_default,sizeof(firstactivetestv2_y2_default));
memcpy(&consts->firstactivetestv3_t1_,&firstactivetestv3_t1_default,sizeof(firstactivetestv3_t1_default));
memcpy(&consts->firstactivetestv3_t2_,&firstactivetestv3_t2_default,sizeof(firstactivetestv3_t2_default));
memcpy(&consts->firstactivetestv3_y1_,&firstactivetestv3_y1_default,sizeof(firstactivetestv3_y1_default));
memcpy(&consts->firstactivetestv3_y2_,&firstactivetestv3_y2_default,sizeof(firstactivetestv3_y2_default));
