/*  ------------------------------------------------------
     Routine name:  prog_1
     Description:   
     Project file:  Шаблон.prt

------------------------------------------------------  */

int i;
int j;
int c;
ret = 0;
memcpy(&state_vars->prog_1v0_out_0_,&prog_1v0_out_0_default,sizeof(prog_1v0_out_0_default));
memcpy(&state_vars->prog_1v1_out_0_,&prog_1v1_out_0_default,sizeof(prog_1v1_out_0_default));
memcpy(&state_vars->prog_1v2_out_0_,&prog_1v2_out_0_default,sizeof(prog_1v2_out_0_default));
memcpy(&state_vars->prog_1v3_out_0_,&prog_1v3_out_0_default,sizeof(prog_1v3_out_0_default));
memcpy(&state_vars->prog_1v3_my_global_external_var_,&prog_1v3_my_global_external_var_default,sizeof(prog_1v3_my_global_external_var_default));
