/*  ------------------------------------------------------
     Routine name:  my_diagram
        Generated:  02.12.2011 11:54:41
      Description:  
     Project file:  —хема автоматики.prt

------------------------------------------------------  */

ret = 0;
memcpy(&my_diagramv5_out_0,&my_diagramv5_out_0_default,sizeof(my_diagramv5_out_0_default));
memcpy(&my_diagramv6_out_0,&my_diagramv6_out_0_default,sizeof(my_diagramv6_out_0_default));
memcpy(&my_diagramv10_out_0,&my_diagramv10_out_0_default,sizeof(my_diagramv10_out_0_default));
memcpy(&my_diagramv11_out_0,&my_diagramv11_out_0_default,sizeof(my_diagramv11_out_0_default));
memcpy(&my_diagramv12_out_0,&my_diagramv12_out_0_default,sizeof(my_diagramv12_out_0_default));
memcpy(&my_diagramv13_out_0,&my_diagramv13_out_0_default,sizeof(my_diagramv13_out_0_default));
memcpy(&my_diagramv0_out_0,&my_diagramv0_out_0_default,sizeof(my_diagramv0_out_0_default));
memcpy(&my_diagramv1_a,&my_diagramv1_a_default,sizeof(my_diagramv1_a_default));
memcpy(&my_diagramv2_a,&my_diagramv2_a_default,sizeof(my_diagramv2_a_default));
memcpy(&my_diagramv3_a,&my_diagramv3_a_default,sizeof(my_diagramv3_a_default));
memcpy(&my_diagramv5_k,&my_diagramv5_k_default,sizeof(my_diagramv5_k_default));
memcpy(&my_diagramv6_k,&my_diagramv6_k_default,sizeof(my_diagramv6_k_default));
memcpy(&my_diagramv9_a,&my_diagramv9_a_default,sizeof(my_diagramv9_a_default));
memcpy(&my_diagramv17_a,&my_diagramv17_a_default,sizeof(my_diagramv17_a_default));
memcpy(&my_diagramv17_b,&my_diagramv17_b_default,sizeof(my_diagramv17_b_default));
memcpy(&my_diagramv17_c,&my_diagramv17_c_default,sizeof(my_diagramv17_c_default));
memcpy(&my_diagramv18_a,&my_diagramv18_a_default,sizeof(my_diagramv18_a_default));
memcpy(&my_diagramv18_b,&my_diagramv18_b_default,sizeof(my_diagramv18_b_default));
memcpy(&my_diagramv19_a,&my_diagramv19_a_default,sizeof(my_diagramv19_a_default));
memcpy(&my_diagramv20_a,&my_diagramv20_a_default,sizeof(my_diagramv20_a_default));
memcpy(&my_diagramv22_a,&my_diagramv22_a_default,sizeof(my_diagramv22_a_default));
memcpy(&my_diagramv24_a,&my_diagramv24_a_default,sizeof(my_diagramv24_a_default));
