/*  ------------------------------------------------------
     Routine name:  fl_controller_fp
     Description:   
     Project file:  fl_controller_fp.prt

------------------------------------------------------  */

/*       Local stack variables                */
int i;
int j;
int c;
fix16_t tmp1;
fix16_t tmp2;
fix16_t tmp3;
fix16_t tmp4;
fix16_t tmp5;
fix16_t tmp6;
char f;
char tmp_f_1;
char u_s;
char u_r;
ret = 0;

