/*  ------------------------------------------------------
     Routine name:  fl_controller
     Description:   
     Project file:  fl_controller_fp.prt

------------------------------------------------------  */

/*       Local stack variables                */
int i;
int j;
int c;
double tmp1;
double tmp2;
double tmp3;
double tmp4;
double tmp5;
double tmp6;
char f;
char tmp_f_1;
char u_s;
char u_r;
ret = 0;

