/*  ------------------------------------------------------
     Routine name:  my_diagram
     Description:   
     Project file:  Шаблон.prt

------------------------------------------------------  */

int i;
int j;
int c;
ret = 0;
memcpy(&v0x,&v0x_default,sizeof(v0x_default));
memcpy(&state_vars->my_diagramv0_out_0_,&my_diagramv0_out_0_default,sizeof(my_diagramv0_out_0_default));
memcpy(&state_vars->my_diagramv0_out_1_,&my_diagramv0_out_1_default,sizeof(my_diagramv0_out_1_default));
state_vars->my_diagramv0_out_1_=(0);
v0_sinit__1:
;
