/*  ------------------------------------------------------
     Routine name:  test
     Description:   
     Project file:  Шаблон.prt

------------------------------------------------------  */

int i;
int j;
int c;
ret = 0;
memcpy(&state_vars->testv0_out_0_,&testv0_out_0_default,sizeof(testv0_out_0_default));
memcpy(&state_vars->testv1_out_0_,&testv1_out_0_default,sizeof(testv1_out_0_default));
memcpy(&state_vars->testv2_t_,&testv2_t_default,sizeof(testv2_t_default));
memcpy(&state_vars->testv2_out_1_,&testv2_out_1_default,sizeof(testv2_out_1_default));
memcpy(&state_vars->testv2_out_0_,&testv2_out_0_default,sizeof(testv2_out_0_default));
memcpy(&state_vars->testv2_timer_,&testv2_timer_default,sizeof(testv2_timer_default));
memcpy(&consts->testv2_tau_,&testv2_tau_default,sizeof(testv2_tau_default));
