/*  ------------------------------------------------------
     Routine name:  my_diagram_vec
     Description:   
     Project file:  Шаблон привязки к векторным свойствам на Си.prt

------------------------------------------------------  */

int i;
int j;
int c;
ret = 0;
memcpy(&state_vars->my_diagram_vecv0_out_0_,&my_diagram_vecv0_out_0_default,sizeof(my_diagram_vecv0_out_0_default));
memcpy(&state_vars->my_diagram_vecv1_out_0_,&my_diagram_vecv1_out_0_default,sizeof(my_diagram_vecv1_out_0_default));
memcpy(&state_vars->my_diagram_vecv2_out_0_,&my_diagram_vecv2_out_0_default,sizeof(my_diagram_vecv2_out_0_default));
