/*  ------------------------------------------------------
     Routine name:  my_diagram
        Generated:  02.12.2011 11:55:02
      Description:  
     Project file:  Пример прямого написания программы на Си.prt

------------------------------------------------------  */

/*       Local stack variables                */
int i;
int j;
int c;
double tmp1;
char f;
char u_s;
char u_r;
  
static double v1_w;
v1_w = 10;
ret = 0;


/* Index=1
   UID=1
   GeneratorClassName=TLanguage
   Name=LangBlock4
   Type=Язык программирования */

my_diagramv1_out_0=my_diagramv1_out_0+1;
