/*  ------------------------------------------------------
     Routine name:  my_diagram
        Generated:  02.12.2011 11:55:02
      Description:  
     Project file:  Пример прямого написания программы на Си.prt

------------------------------------------------------  */

ret = 0;
memcpy(&my_diagramv1_dyn_var,&my_diagramv1_dyn_var_default,sizeof(my_diagramv1_dyn_var_default));
memcpy(&my_diagramv0_out_0,&my_diagramv0_out_0_default,sizeof(my_diagramv0_out_0_default));
memcpy(&my_diagramv1_out_0,&my_diagramv1_out_0_default,sizeof(my_diagramv1_out_0_default));
my_diagramv1_out_0=1;
