/*  ------------------------------------------------------
     Routine name:  my_diagram
     Description:   
     Project file:  Ўаблон пр€мого написани€ программы на —и.prt

------------------------------------------------------  */

/*       Local stack variables                */
int i;
int j;
int c;
int itmp1;
int itmp2;
double tmp1;
double tmp2;
double tmp3;
double tmp4;
double tmp5;
double tmp6;
double tmp7;
char f;
char tmp_f_1;
char u_s;
char u_r;
  
static double v1_w;
v1_w = 10;
ret = 0;


/* Index=1
   UID=1
   GeneratorClassName=TLanguage
   Name=LangBlock4
   Type=язык программировани€ */

state_vars->my_diagramv1_out_0_=state_vars->my_diagramv1_out_0_+1;
