/*  ------------------------------------------------------
     Routine name:  my_diagram
     Description:   
     Project file:  Шаблон прямого написания программы на Си.prt

------------------------------------------------------  */

int i;
int j;
int c;
ret = 0;
memcpy(&my_diagramv1_dyn_var,&my_diagramv1_dyn_var_default,sizeof(my_diagramv1_dyn_var_default));
memcpy(&state_vars->my_diagramv0_out_0_,&my_diagramv0_out_0_default,sizeof(my_diagramv0_out_0_default));
memcpy(&state_vars->my_diagramv1_out_0_,&my_diagramv1_out_0_default,sizeof(my_diagramv1_out_0_default));
state_vars->my_diagramv1_out_0_=1;
